### ISSUE TITLE
Unable to provide placeholders as arguments in the configuration file

### ISSUE THREAD

**Issue by gattupalliaditya** [markgardner/node-flywaydb#14]
Have a flywayArgs file with the following configuration
  flywayArgs: {
         url : ...,
         user: ...,
         password: ...,
          .
          .
          .
        placeholders:
        {
            name: "value"
        }
    }

Without placeholders argument in the config the migration works fine but with it throws the following error

```
ERROR: Unknown configuration property: flyway.placeholders
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```
All other arguments given in https://flywaydb.org/documentation/commandline/migrate seem to be working fine.

**Comment by markgardner** [comment]
it should work if you don't use nested objects. I'd like to avoid custom arg translations since it will change from version to version of flyway.

Checkout out this config:
```
module.exports = {
    flywayArgs: {
        url: 'jdbc:postgresql://localhost/postgres',
        schemas: 'public',
        locations: 'filesystem:sample/sql',
        user: 'postgres',
        password: 'example',
        sqlMigrationSuffixes: '.pgsql',
        'placeholders.aplaceholder': 'value',
        'placeholders.otherplaceholder': 'value123',
    },
};
```
