### ISSUE TITLE
Request library has been marked deprecated

### ISSUE THREAD

**Issue by joey-kendall** [markgardner/node-flywaydb#15]
While running the migrate command in my build system I found output logging that indicated that request had been deprecated:

https://github.com/request/request

**Comment by markgardner** [comment]
@joey-kendall thanks for the heads up. I'll start looking for an alternative or even just use the standard lib. Any suggestions?

**Comment by joey-kendall** [comment]
They have posted an issue with a list of replacement ideas:
https://github.com/request/request/issues/3143
Of them I've only used Axios and Unfetch ...

**Comment by markgardner** [comment]
This has been fixed in 3.0.0
