### ISSUE TITLE
Config Values Override Env Values

### ISSUE THREAD

**Issue by tecklund** [markgardner/node-flywaydb#17]
Configuration can't be overridden by ENV vars because the code 

```
function configFlywayArgs(config) {
    const flywayArgs = config.flywayArgs || {};
    const flywayArgsKeys = Object.keys(flywayArgs);

    return flywayArgsKeys.map(function(key) {
        return `-${key}=${flywayArgs[key]}`;
    });
}
```
sets everything in the required config file via command line arg, which overrides environment variables https://flywaydb.org/documentation/commandline/#overriding-order

**Comment by markgardner** [comment]
+1 I'll get that fixed.

**Comment by markgardner** [comment]
Just reviewed this a second time. This is functioning as expected. The wrapper won't pass any extra command line args that it receives to the flyway process. It would be a maintenance nightmare to try to keep in step with the core flyway project. Instead, you can use the config file to setup the flyway commands. See the sample config for an example.

I did change the the wrapper to allow for the main config export to be a function to allow you to code in some extra command line parsing.

https://github.com/markgardner/node-flywaydb/commit/36fa94616c94105193a4cdd3e9cddf7d13d39b42

**Comment by tecklund** [comment]
Cool, I went with 
```
const params = process.env;

module.exports = {
  flywayArgs: {
      url: params.FLYWAY_URL || 'jdbc:postgresql://localhost:5432/db',
      schemas: 'myschema',
      locations: 'filesystem:migrations',
      user: params.FLYWAY_USERNAME || params.USER,
      password: params.FLYWAY_PASSWORD || 'postgres'
  }
}
```

but a function would be even better. Thanks!
