### ISSUE TITLE
Spelling of Maven in config is incorrect.

### ISSUE THREAD

**Issue by campbellbartlett** [markgardner/node-flywaydb#23]
https://github.com/markgardner/node-flywaydb/blob/6b0968ff1439cd8fa4d6a57d39e125784ea02ce3/lib/download.js#L259

Hey 👋 
Loving this project so far - works seamlessly with very little effort required!

Just one small thing I've noticed is that in the config file Maven is spelt Mavin (with an i instead of an e). Was there a reason for this or is it a typo? If it's a typo I'm happy to open a PR to fix it.

**Comment by markgardner** [comment]
ahh good catch, that's a typo. A PR would be most welcome.

**Comment by markgardner** [comment]
Fixed by #24
