### ISSUE TITLE
environment variables in config.js

### ISSUE THREAD

**Issue by GwFreak01** [markgardner/node-flywaydb#28]
Not really an issue, but is it possible to use environment variables inside the config.js file? Im running into a problem where the script states that I have an invalid character.

```
require("dotenv").config();

// This can be a function or an object literal.
module.exports = function() {
    return {
        flywayArgs: {
            url: `jdbc:postgresql://${process.env.POSTGRES_HOST}:${process.env.POSTGRES_PORT}/${process.env.POSTGRES_DB}`,
            schemas: `${process.env.POSTGRES_SCHEMA}`,
            locations: 'filesystem:/sql',
            user: `${process.env.POSTGRES_USER}`,
            password: `${process.env.POSTGRES_PASSWORD}`,
            sqlMigrationSuffixes: '.sql',
            baselineOnMigrate: true,
            dryRunOutput: 'dryrun.sql'
            ....
        },```

**Comment by markgardner** [comment]
You should be able do this, might be worth creating a test script that requires the config.js and runs the exported function to see if there is a javascript error that isn't being correctly reported by the library.

Let me know if it was an error and I can work on improving the error reporting process.

**Comment by GwFreak01** [comment]
Ok so I got a bit further on it. However, I'm running into a new issue when it tries to read my sql scripts

I am running this package from a windows machine and needed to create a `/var/test` directory so flyway could be downloaded and then came across this error:
`ERROR: Unable to obtain inputstream for resource: /sql/V202105112307__MC-110_create_account_table.sql`

**Comment by markgardner** [comment]
Sorry for the delay, sounds like a permissions issue. Feel free to re-open if you find that it's an issue with the library.
