### ISSUE TITLE
Broken aliases in 'legal' folder cause error when running Babel

### ISSUE THREAD

**Issue by ekuntzHautelook** [markgardner/node-flywaydb#30]
### Issue

I have a NodeJS app that uses babel to convert the ES6 syntax to ES5, but when running the `babel` command it fails stating `ENOENT: no such file or directory, stat 'node_modules/node-flywaydb/jlib/flyway-commandline-7.9.1/flyway-7.9.1/jre/legal/java.compiler/ASSEMBLY_EXCEPTION'`

I fixed the first alias and the error moved to the next file in the same directory.  Then I deleted the `legal` folder and the error went away.  

### Possible Solution
Can the `flyway-<version>/jre/legal` directory be removed after download?  The aliases references themselves which causes Babel to error when attempting to build.  I had created an issue [here](https://github.com/flyway/flyway/issues/3192) with flyway directly, but they stated that they do not have control over that folder and it can be deleted.

**Comment by markgardner** [comment]
Hi, you would need to remove something like that in your tooling layer. It would be difficult to properly maintain a delete list after download with the jre folder.

Another solution would be to add the `node_modules/node-flywaydb/**` to the babel exclude path.
