### ISSUE TITLE
Breaks when ran from within a directory with a space in the name

### ISSUE THREAD

**Issue by n8jadams** [markgardner/node-flywaydb#32]
On a Windows machine today I ran into the problem where the flyway command broke with this error:

`C:\Users\Nate` is not recognized as an internal or external command

I realized it's because I was running it from a directory within `C:\Users\Nate Adams\...` but the space in that path wasn't being escaped when the actual flyway command occurs. Moving to different directory fixed it. 

Hopefully escaping those spaces in directory names is a small bug to fix...

**Comment by markgardner** [comment]
Thanks for reporting this, it ended up being a kinda weird fix with how windows parses the command. Switching to using a shell (cmd.exe) fixes the problem.

Here's the commit https://github.com/markgardner/node-flywaydb/commit/239c277f693ee034bfae889e8083bba5044cac4f
