### ISSUE TITLE
Getting error in downloading stage

### ISSUE THREAD

**Issue by yoavain-sundaysky** [markgardner/node-flywaydb#8]
This used to work a couple of weeks ago, so maybe something in the new version broke it.
Platform: Windows

See log below (happens on an environment with regular node installation. It's not related to my nvm)

`
DOWNLOADING https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/maven-metadata.xml
DOWNLOADING https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-windows-x64.zip
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\username\AppData\Roaming\nvm\v10.15.3\node_modules\node-flywaydb\jlib\flyway-commandline-5.2.4\flyway-5.2.4\flyway ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hub@1.0.0 flyway-info: `flyway --configfile=db/conf/flyway.js info`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hub@1.0.0 flyway-info script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by yoavain-sundaysky** [comment]
Version 0.1.6 works fine

**Comment by markgardner** [comment]
I’ll test on Windows. Seems work for me on Mac and Linux.

**Comment by soorur** [comment]
Same on Windows 10

**Comment by markgardner** [comment]
v2.0.1 should fix this.
